const APIconfig = {
  baseURL: `${import.meta.env.VITE_BACKEND_URL}/api/v1`,
  login: "/login",
  register: "/register",
  logout: "/logout",
  passwordchange: "/changepassword",
  googleAuth: "/google-auth",
  getme: "/getme",
  getDR: "/getdr",
  addDR: "/adddr",
  rmDR: "/rmdr",
  editDR: "/editdr",
  completeDR: "/completedr",
  addTR: "/addtr",
  getTR: "/gettr",
  rmTR: "/rmtr",
  editTR: "/edittr",
  completeTR: "/completetr",
  editUser: "/edituser",
  sendEmailVerification: "/sendemailverification",
  TokenEmailVerification: "/tokenemailverify",
  traitTON: "/traitTON",
  sendPasswordResetToken: "/sendresetpasswordtoken",
  resetPassword: "/resetpassword",
  deleteAccount: "/deletemyaccount",
};
export { APIconfig };
